# Watch face sources, shared by the watch build (CMakeLists.txt) and the simulator.
# wf_bind.c, wf_comp.c, wf_json.c, wf_decl.c, wf_cfg.c and wf_shift.c are pure C
# (host tests: test_wf_bind, test_wf_decl, test_wf_cfg, test_wf_shift).
set(S3W_WF_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/wf_bind.c
    ${CMAKE_CURRENT_LIST_DIR}/wf_comp.c
    ${CMAKE_CURRENT_LIST_DIR}/wf_json.c
    ${CMAKE_CURRENT_LIST_DIR}/wf_decl.c
    ${CMAKE_CURRENT_LIST_DIR}/wf_cfg.c
    ${CMAKE_CURRENT_LIST_DIR}/wf_shift.c
    ${CMAKE_CURRENT_LIST_DIR}/wf_decl_face.c
    ${CMAKE_CURRENT_LIST_DIR}/wf_engine.c
    ${CMAKE_CURRENT_LIST_DIR}/wf_picker.c
    ${CMAKE_CURRENT_LIST_DIR}/wf_widgets.c
    ${CMAKE_CURRENT_LIST_DIR}/face_digital.c
    ${CMAKE_CURRENT_LIST_DIR}/face_analog.c
    ${CMAKE_CURRENT_LIST_DIR}/face_text.c)

# Sample declarative faces: samples/<id>/face.json embedded as C arrays in a generated
# wf_samples.c (wf_priv.h: wf_samples[]), re-generated when a sample changes.
# Skipped in ESP-IDF's early requirements scan (script mode).
set(S3W_WF_SAMPLES_DIR ${CMAKE_CURRENT_LIST_DIR}/samples)
if(NOT CMAKE_BUILD_EARLY_EXPANSION)
    file(GLOB S3W_WF_SAMPLE_JSON CONFIGURE_DEPENDS ${S3W_WF_SAMPLES_DIR}/*/face.json)
    set(_wf_arrays "")
    set(_wf_table "")
    set(_wf_n 0)
    foreach(_wf_json ${S3W_WF_SAMPLE_JSON})
        file(READ ${_wf_json} _wf_hex HEX)
        string(LENGTH "${_wf_hex}" _wf_len)
        math(EXPR _wf_len "${_wf_len} / 2")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _wf_bytes "${_wf_hex}")
        file(RELATIVE_PATH _wf_rel ${CMAKE_CURRENT_LIST_DIR} ${_wf_json})
        string(APPEND _wf_arrays "static const char SAMPLE_${_wf_n}[] = {${_wf_bytes}0x00};\n")
        string(APPEND _wf_table "    {\"watchfaces/${_wf_rel}\", SAMPLE_${_wf_n}, ${_wf_len}},\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_wf_json})
        math(EXPR _wf_n "${_wf_n} + 1")
    endforeach()
    file(CONFIGURE OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/wf_samples.c @ONLY CONTENT
"// Generated by components/watchfaces/sources.cmake from samples/*/face.json. Do not edit.
#include \"wf_priv.h\"

${_wf_arrays}
const wf_sample_t wf_samples[] = {
${_wf_table}};
const size_t wf_sample_count = ${_wf_n};
")
    list(APPEND S3W_WF_SRCS ${CMAKE_CURRENT_BINARY_DIR}/wf_samples.c)
endif()
