# Portable UI sources (LVGL + HAL only), shared by the watch build
# (ui_framework/CMakeLists.txt) and the simulator so the two lists cannot drift.
set(S3W_UI_PORTABLE_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/ui_root.c
    ${CMAKE_CURRENT_LIST_DIR}/theme.c
    ${CMAKE_CURRENT_LIST_DIR}/nav.c
    ${CMAKE_CURRENT_LIST_DIR}/overlay.c
    ${CMAKE_CURRENT_LIST_DIR}/widgets.c
    ${CMAKE_CURRENT_LIST_DIR}/label_fit.c
    ${CMAKE_CURRENT_LIST_DIR}/gallery.c
    ${CMAKE_CURRENT_LIST_DIR}/power_menu.c
    ${CMAKE_CURRENT_LIST_DIR}/watch_only.c
    # Generated by tools/fonts/gen_fonts.sh
    ${CMAKE_CURRENT_LIST_DIR}/fonts/s3w_font_display_96.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/s3w_font_display_bold_160.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/s3w_font_display_light_96.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/s3w_font_title_32.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/s3w_font_body_26.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/s3w_font_caption_22.c)
