/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.2 */

#include "envelope.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(s3w_v1_Envelope, s3w_v1_Envelope, 2)


PB_BIND(s3w_v1_Status, s3w_v1_Status, AUTO)


PB_BIND(s3w_v1_Hello, s3w_v1_Hello, 2)


PB_BIND(s3w_v1_HelloAck, s3w_v1_HelloAck, 2)


PB_BIND(s3w_v1_TimeSync, s3w_v1_TimeSync, AUTO)


PB_BIND(s3w_v1_Ack, s3w_v1_Ack, AUTO)





