/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.2 */

#ifndef PB_S3W_V1_ENVELOPE_PB_H_INCLUDED
#define PB_S3W_V1_ENVELOPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Values for Status.code. Status.code stays int32 so a code unknown to an
 older peer is still delivered instead of decoding as STATUS_OK. */
typedef enum _s3w_v1_StatusCode {
    s3w_v1_StatusCode_STATUS_OK = 0,
    s3w_v1_StatusCode_STATUS_UNSUPPORTED = 1,
    s3w_v1_StatusCode_STATUS_INVALID = 2,
    s3w_v1_StatusCode_STATUS_BUSY = 3,
    s3w_v1_StatusCode_STATUS_NO_SPACE = 4,
    s3w_v1_StatusCode_STATUS_DENIED = 5,
    s3w_v1_StatusCode_STATUS_INTERNAL = 6,
    s3w_v1_StatusCode_STATUS_LOW_BATTERY = 7
} s3w_v1_StatusCode;

/* Struct definitions */
typedef struct _s3w_v1_Status {
    int32_t code; /* StatusCode */
    char message[96]; /* ≤ 95 bytes, for logs; not shown to users */
} s3w_v1_Status;

/* Phone → watch, first message of a session (docs/06 §4). */
typedef struct _s3w_v1_Hello {
    uint32_t proto_major;
    uint32_t proto_minor;
    char app_version[32]; /* ≤ 31 bytes */
    pb_size_t caps_count;
    char caps[32][24]; /* ≤ 32 entries, each ≤ 23 bytes, e.g. "notif.actions" */
    char phone_model[64]; /* ≤ 63 bytes */
    char locale[36]; /* BCP 47, ≤ 35 bytes */
    char tz_name[64]; /* IANA, ≤ 63 bytes */
} s3w_v1_Hello;

/* Watch → phone, reply to Hello. Envelope.status = UNSUPPORTED on major mismatch. */
typedef struct _s3w_v1_HelloAck {
    uint32_t proto_major;
    uint32_t proto_minor;
    char fw_version[32]; /* ≤ 31 bytes */
    char hw_rev[16]; /* ≤ 15 bytes */
    char serial[32]; /* ≤ 31 bytes */
    pb_size_t caps_count;
    char caps[32][24]; /* ≤ 32 entries, each ≤ 23 bytes */
    uint32_t battery_pct; /* 0-100 */
    uint32_t storage_free_kb;
    uint32_t storage_total_kb;
    uint32_t api_level; /* mini app API level (docs/05) */
} s3w_v1_HelloAck;

/* Phone → watch: wall-clock time and time zone. */
typedef struct _s3w_v1_TimeSync {
    int64_t unix_ms;
    char tz_posix[64]; /* POSIX TZ string, e.g. "<+06>-6", ≤ 63 bytes */
    char tz_name[64]; /* IANA, ≤ 63 bytes */
    bool is_24h;
} s3w_v1_TimeSync;

/* Reply body for requests that return no data; the outcome is Envelope.status. */
typedef struct _s3w_v1_Ack {
    char dummy_field;
} s3w_v1_Ack;

/* Every control-channel message is one Envelope (docs/06 §3). */
typedef struct _s3w_v1_Envelope {
    uint32_t id; /* sender-assigned; non-zero for requests, 0 for events */
    uint32_t reply_to; /* id of the request this answers; 0 = not a reply */
    bool has_status;
    s3w_v1_Status status; /* set on replies */
    pb_size_t which_body;
    union {
        s3w_v1_Hello hello;
        s3w_v1_HelloAck hello_ack;
        s3w_v1_TimeSync time_sync;
        s3w_v1_Ack ack;
    } body;
} s3w_v1_Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _s3w_v1_StatusCode_MIN s3w_v1_StatusCode_STATUS_OK
#define _s3w_v1_StatusCode_MAX s3w_v1_StatusCode_STATUS_LOW_BATTERY
#define _s3w_v1_StatusCode_ARRAYSIZE ((s3w_v1_StatusCode)(s3w_v1_StatusCode_STATUS_LOW_BATTERY+1))








/* Initializer values for message structs */
#define s3w_v1_Envelope_init_default             {0, 0, false, s3w_v1_Status_init_default, 0, {s3w_v1_Hello_init_default}}
#define s3w_v1_Status_init_default               {0, ""}
#define s3w_v1_Hello_init_default                {0, 0, "", 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}, "", "", ""}
#define s3w_v1_HelloAck_init_default             {0, 0, "", "", "", 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}, 0, 0, 0, 0}
#define s3w_v1_TimeSync_init_default             {0, "", "", 0}
#define s3w_v1_Ack_init_default                  {0}
#define s3w_v1_Envelope_init_zero                {0, 0, false, s3w_v1_Status_init_zero, 0, {s3w_v1_Hello_init_zero}}
#define s3w_v1_Status_init_zero                  {0, ""}
#define s3w_v1_Hello_init_zero                   {0, 0, "", 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}, "", "", ""}
#define s3w_v1_HelloAck_init_zero                {0, 0, "", "", "", 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}, 0, 0, 0, 0}
#define s3w_v1_TimeSync_init_zero                {0, "", "", 0}
#define s3w_v1_Ack_init_zero                     {0}

/* Field tags (for use in manual encoding/decoding) */
#define s3w_v1_Status_code_tag                   1
#define s3w_v1_Status_message_tag                2
#define s3w_v1_Hello_proto_major_tag             1
#define s3w_v1_Hello_proto_minor_tag             2
#define s3w_v1_Hello_app_version_tag             3
#define s3w_v1_Hello_caps_tag                    4
#define s3w_v1_Hello_phone_model_tag             5
#define s3w_v1_Hello_locale_tag                  6
#define s3w_v1_Hello_tz_name_tag                 7
#define s3w_v1_HelloAck_proto_major_tag          1
#define s3w_v1_HelloAck_proto_minor_tag          2
#define s3w_v1_HelloAck_fw_version_tag           3
#define s3w_v1_HelloAck_hw_rev_tag               4
#define s3w_v1_HelloAck_serial_tag               5
#define s3w_v1_HelloAck_caps_tag                 6
#define s3w_v1_HelloAck_battery_pct_tag          7
#define s3w_v1_HelloAck_storage_free_kb_tag      8
#define s3w_v1_HelloAck_storage_total_kb_tag     9
#define s3w_v1_HelloAck_api_level_tag            10
#define s3w_v1_TimeSync_unix_ms_tag              1
#define s3w_v1_TimeSync_tz_posix_tag             2
#define s3w_v1_TimeSync_tz_name_tag              3
#define s3w_v1_TimeSync_is_24h_tag               4
#define s3w_v1_Envelope_id_tag                   1
#define s3w_v1_Envelope_reply_to_tag             2
#define s3w_v1_Envelope_status_tag               3
#define s3w_v1_Envelope_hello_tag                10
#define s3w_v1_Envelope_hello_ack_tag            11
#define s3w_v1_Envelope_time_sync_tag            12
#define s3w_v1_Envelope_ack_tag                  13

/* Struct field encoding specification for nanopb */
#define s3w_v1_Envelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   reply_to,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,hello,body.hello),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,hello_ack,body.hello_ack),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,time_sync,body.time_sync),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ack,body.ack),  13)
#define s3w_v1_Envelope_CALLBACK NULL
#define s3w_v1_Envelope_DEFAULT NULL
#define s3w_v1_Envelope_status_MSGTYPE s3w_v1_Status
#define s3w_v1_Envelope_body_hello_MSGTYPE s3w_v1_Hello
#define s3w_v1_Envelope_body_hello_ack_MSGTYPE s3w_v1_HelloAck
#define s3w_v1_Envelope_body_time_sync_MSGTYPE s3w_v1_TimeSync
#define s3w_v1_Envelope_body_ack_MSGTYPE s3w_v1_Ack

#define s3w_v1_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    code,              1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2)
#define s3w_v1_Status_CALLBACK NULL
#define s3w_v1_Status_DEFAULT NULL

#define s3w_v1_Hello_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   proto_major,       1) \
X(a, STATIC,   SINGULAR, UINT32,   proto_minor,       2) \
X(a, STATIC,   SINGULAR, STRING,   app_version,       3) \
X(a, STATIC,   REPEATED, STRING,   caps,              4) \
X(a, STATIC,   SINGULAR, STRING,   phone_model,       5) \
X(a, STATIC,   SINGULAR, STRING,   locale,            6) \
X(a, STATIC,   SINGULAR, STRING,   tz_name,           7)
#define s3w_v1_Hello_CALLBACK NULL
#define s3w_v1_Hello_DEFAULT NULL

#define s3w_v1_HelloAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   proto_major,       1) \
X(a, STATIC,   SINGULAR, UINT32,   proto_minor,       2) \
X(a, STATIC,   SINGULAR, STRING,   fw_version,        3) \
X(a, STATIC,   SINGULAR, STRING,   hw_rev,            4) \
X(a, STATIC,   SINGULAR, STRING,   serial,            5) \
X(a, STATIC,   REPEATED, STRING,   caps,              6) \
X(a, STATIC,   SINGULAR, UINT32,   battery_pct,       7) \
X(a, STATIC,   SINGULAR, UINT32,   storage_free_kb,   8) \
X(a, STATIC,   SINGULAR, UINT32,   storage_total_kb,   9) \
X(a, STATIC,   SINGULAR, UINT32,   api_level,        10)
#define s3w_v1_HelloAck_CALLBACK NULL
#define s3w_v1_HelloAck_DEFAULT NULL

#define s3w_v1_TimeSync_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    unix_ms,           1) \
X(a, STATIC,   SINGULAR, STRING,   tz_posix,          2) \
X(a, STATIC,   SINGULAR, STRING,   tz_name,           3) \
X(a, STATIC,   SINGULAR, BOOL,     is_24h,            4)
#define s3w_v1_TimeSync_CALLBACK NULL
#define s3w_v1_TimeSync_DEFAULT NULL

#define s3w_v1_Ack_FIELDLIST(X, a) \

#define s3w_v1_Ack_CALLBACK NULL
#define s3w_v1_Ack_DEFAULT NULL

extern const pb_msgdesc_t s3w_v1_Envelope_msg;
extern const pb_msgdesc_t s3w_v1_Status_msg;
extern const pb_msgdesc_t s3w_v1_Hello_msg;
extern const pb_msgdesc_t s3w_v1_HelloAck_msg;
extern const pb_msgdesc_t s3w_v1_TimeSync_msg;
extern const pb_msgdesc_t s3w_v1_Ack_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define s3w_v1_Envelope_fields &s3w_v1_Envelope_msg
#define s3w_v1_Status_fields &s3w_v1_Status_msg
#define s3w_v1_Hello_fields &s3w_v1_Hello_msg
#define s3w_v1_HelloAck_fields &s3w_v1_HelloAck_msg
#define s3w_v1_TimeSync_fields &s3w_v1_TimeSync_msg
#define s3w_v1_Ack_fields &s3w_v1_Ack_msg

/* Maximum encoded size of messages (where known) */
#define S3W_V1_ENVELOPE_PB_H_MAX_SIZE            s3w_v1_Envelope_size
#define s3w_v1_Ack_size                          0
#define s3w_v1_Envelope_size                     1137
#define s3w_v1_HelloAck_size                     919
#define s3w_v1_Hello_size                        1012
#define s3w_v1_Status_size                       108
#define s3w_v1_TimeSync_size                     143

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
