// Design tokens and theme (docs/04-ui-ux.md §2). Values here are the single source
// for the watch; android/core/designsystem mirrors them for previews.
#pragma once

#include <stdint.h>
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// --- Colour ----------------------------------------------------------------------
#define UI_COLOR_BG          0x000000
#define UI_COLOR_SURFACE     0x1C1C1E
#define UI_COLOR_SURFACE_HI  0x2C2C2E
#define UI_COLOR_TEXT        0xFFFFFF
#define UI_COLOR_TEXT_DIM    0x9A9AA0
#define UI_COLOR_SUCCESS     0x30D158
#define UI_COLOR_WARNING     0xFFD60A
#define UI_COLOR_DANGER      0xFF453A
#define UI_COLOR_MOVE        0xFA114F
#define UI_COLOR_EXERCISE    0xA6FF00
#define UI_COLOR_STAND       0x00F0FF

/** User-selectable accent colours; UI_ACCENT_BLUE is the default. */
typedef enum {
    UI_ACCENT_BLUE = 0,
    UI_ACCENT_GREEN,
    UI_ACCENT_ORANGE,
    UI_ACCENT_PINK,
    UI_ACCENT_PURPLE,
    UI_ACCENT_TEAL,
    UI_ACCENT_COUNT,
} ui_accent_t;

// --- Shape and spacing (px) ---------------------------------------------------------
#define UI_RADIUS_CARD    28
#define UI_RADIUS_BUTTON  32
#define UI_SPACE_XS       4
#define UI_SPACE_S        8
#define UI_SPACE_M        16
#define UI_SPACE_L        24
#define UI_SPACE_XL       32
#define UI_TOUCH_MIN      64 // minimum touch target (docs/04 §1)
/** Content inset from the rounded glass corners. Estimate until measured on the
 *  device (docs/04: corner radius ~60 px; a 60 px corner clears at ~18 px in). */
#define UI_SAFE_INSET     24

// --- Motion (ms, ease-out) -------------------------------------------------------
#define UI_MOTION_FAST    120
#define UI_MOTION_NORMAL  200

// --- Typography --------------------------------------------------------------------
// Inter, generated by tools/fonts/gen_fonts.sh (Latin, Greek, Cyrillic + LV_SYMBOL_*).
// The display fonts have digits and ": . , - + %" only.
LV_FONT_DECLARE(s3w_font_display_96)
LV_FONT_DECLARE(s3w_font_display_bold_160)
LV_FONT_DECLARE(s3w_font_display_light_96)
LV_FONT_DECLARE(s3w_font_title_32)
LV_FONT_DECLARE(s3w_font_body_26)
LV_FONT_DECLARE(s3w_font_caption_22)

#define UI_FONT_DISPLAY (&s3w_font_display_96)
#define UI_FONT_TITLE   (&s3w_font_title_32)
#define UI_FONT_BODY    (&s3w_font_body_26)
#define UI_FONT_CAPTION (&s3w_font_caption_22)
/** Watch faces: Digital Bold's stacked digits, and light digits (AOD, Minimal). */
#define UI_FONT_DISPLAY_BOLD  (&s3w_font_display_bold_160)
#define UI_FONT_DISPLAY_LIGHT (&s3w_font_display_light_96)

/** Display font with tabular (equal-width) digits, so a running clock does not jitter. */
const lv_font_t *ui_font_display_tabular(void);
/** Tabular-digit wrapper of any of the UI_FONT_DISPLAY* fonts (NULL for others). */
const lv_font_t *ui_font_tabular(const lv_font_t *display_font);

// --- Theme -------------------------------------------------------------------------

/** Install the S3Wear theme (LVGL default dark theme + token overrides) on disp.
 *  Call once with LVGL locked, before creating screens. */
void ui_theme_init(lv_display_t *disp);

/** Change the accent colour and restyle every existing object. */
void ui_theme_set_accent(ui_accent_t accent);
ui_accent_t ui_theme_get_accent(void);
lv_color_t ui_theme_accent_color(void);

static inline lv_color_t ui_color(uint32_t hex) { return lv_color_hex(hex); }

#ifdef __cplusplus
}
#endif
