#!/usr/bin/env bash
# Regenerate everything derived from protocol/proto/*.proto.
#
#   tools/gen_proto.sh          regenerate
#   tools/gen_proto.sh --check  fail if committed output is stale (CI)
#
# Outputs:
#   firmware/components/proto/       nanopb C (committed; never edit by hand)
#   protocol/testvectors/*.bin       golden vectors encoded from *.json (committed)
#   android :core:protocol           Wire Kotlin, generated by Gradle at build time;
#                                    this script runs that task so errors show up here
#
# Tools are pinned and installed into build/protogen/ (no global installs):
# the nanopb generator from the upstream tag that matches the vendored runtime
# (firmware/components/nanopb), protobuf + grpcio-tools in a Python venv.
set -euo pipefail

NANOPB_VERSION=0.4.9.2
NANOPB_SHA256=324e5ef3e9bf2ac549e54f660f852943148f35629ebe88824eacfc37929168f9
PY_REQUIREMENTS="protobuf==7.36.2 grpcio==1.84.0 grpcio-tools==1.84.0"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROTO_DIR="$ROOT/protocol/proto"
VECTORS_DIR="$ROOT/protocol/testvectors"
C_OUT="$ROOT/firmware/components/proto"
WORK="$ROOT/build/protogen"
VENV="$WORK/venv"
NANOPB_DIR="$WORK/nanopb-nanopb-$NANOPB_VERSION"

CHECK=0
case "${1:-}" in
    --check) CHECK=1 ;;
    "") ;;
    *) echo "usage: $0 [--check]" >&2; exit 2 ;;
esac

mkdir -p "$WORK"

# --- Python venv with pinned generator dependencies ---
if [[ ! -x "$VENV/bin/python" || "$(cat "$VENV/.requirements" 2>/dev/null)" != "$PY_REQUIREMENTS" ]]; then
    echo "setting up $VENV"
    rm -rf "$VENV"
    python3 -m venv "$VENV"
    # shellcheck disable=SC2086
    "$VENV/bin/pip" install --quiet --disable-pip-version-check $PY_REQUIREMENTS
    echo "$PY_REQUIREMENTS" > "$VENV/.requirements"
fi
PY="$VENV/bin/python"

# --- nanopb generator, same tag as the vendored runtime ---
if [[ ! -f "$NANOPB_DIR/generator/nanopb_generator.py" ]]; then
    echo "fetching nanopb $NANOPB_VERSION"
    tarball="$WORK/nanopb-$NANOPB_VERSION.tar.gz"
    curl -sSfL -o "$tarball" "https://github.com/nanopb/nanopb/archive/refs/tags/nanopb-$NANOPB_VERSION.tar.gz"
    if command -v sha256sum > /dev/null; then sha=(sha256sum); else sha=(shasum -a 256); fi
    echo "$NANOPB_SHA256  $tarball" | "${sha[@]}" -c --quiet -
    tar -xzf "$tarball" -C "$WORK"
fi

# --- nanopb C ---
tmp_c="$(mktemp -d)"
trap 'rm -rf "$tmp_c"' EXIT
protos=()
while IFS= read -r p; do protos+=("$p"); done < <(cd "$PROTO_DIR" && ls ./*.proto | sed 's|^\./||')
(cd "$PROTO_DIR" && "$PY" "$NANOPB_DIR/generator/nanopb_generator.py" \
    --quiet -I . -D "$tmp_c" "${protos[@]}")

srcs=""
for p in "${protos[@]}"; do srcs+=" \"${p%.proto}.pb.c\""; done
cat > "$tmp_c/CMakeLists.txt" <<CMAKE
# GENERATED by tools/gen_proto.sh from protocol/proto/. Do not edit.
idf_component_register(SRCS$srcs
                       INCLUDE_DIRS "."
                       REQUIRES nanopb)
CMAKE
cat > "$tmp_c/README.md" <<README
# proto (generated)

nanopb $NANOPB_VERSION output for \`protocol/proto/*.proto\`. **Do not edit**: change the
\`.proto\`/\`.options\` files and run \`tools/gen_proto.sh\`.
README

if [[ $CHECK -eq 1 ]]; then
    if ! diff -r "$tmp_c" "$C_OUT" > /dev/null 2>&1; then
        diff -ru "$C_OUT" "$tmp_c" || true
        echo "firmware/components/proto is stale: run tools/gen_proto.sh" >&2
        exit 1
    fi
    echo "nanopb C up to date"
else
    rm -rf "$C_OUT"
    mkdir -p "$C_OUT"
    cp "$tmp_c"/* "$C_OUT/"
    echo "generated firmware/components/proto (${protos[*]})"
fi

# --- golden vectors ---
check_flag=()
[[ $CHECK -eq 1 ]] && check_flag=(--check)
"$PY" "$ROOT/tools/gen_testvectors.py" --proto-dir "$PROTO_DIR" --vectors-dir "$VECTORS_DIR" "${check_flag[@]}"

# --- Wire Kotlin (Gradle) ---
if [[ "${S3W_SKIP_GRADLE:-0}" != 1 ]]; then
    (cd "$ROOT/android" && ./gradlew --quiet :core:protocol:generateMainProtos)
    echo "Wire Kotlin generated (:core:protocol)"
fi
